package com.phuongnn14.tuithantai.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage {
    VIETNAMESE,
    ENGLISH,
    GERMAN,
    HINDI
}

/** Thứ tự hiển thị ngôn ngữ: Anh → Việt → Đức → Ấn Độ (Hindi). */
val AppLanguageOrder = listOf(
    AppLanguage.ENGLISH,
    AppLanguage.VIETNAMESE,
    AppLanguage.GERMAN,
    AppLanguage.HINDI
)

/** Tên hiển thị bản địa của mỗi ngôn ngữ. */
fun AppLanguage.displayName(): String = when (this) {
    AppLanguage.ENGLISH -> "English"
    AppLanguage.VIETNAMESE -> "Tiếng Việt"
    AppLanguage.GERMAN -> "Deutsch"
    AppLanguage.HINDI -> "हिन्दी"
}

/** Cờ quốc gia đại diện cho ngôn ngữ. */
fun AppLanguage.flagEmoji(): String = when (this) {
    AppLanguage.ENGLISH -> "🇬🇧"
    AppLanguage.VIETNAMESE -> "🇻🇳"
    AppLanguage.GERMAN -> "🇩🇪"
    AppLanguage.HINDI -> "🇮🇳"
}

object Localization {
    private val vi = mapOf(
        "app_name" to "Túi Thần Tài",
        "home" to "Trang chủ",
        "history" to "Lịch sử",
        "reports" to "Báo cáo",
        "tools" to "Công cụ",
        "settings" to "Cài đặt",

        "current_balance" to "Tổng số dư khả dụng",
        "income" to "Thu nhập",
        "expense" to "Chi tiêu",
        "recent_transactions" to "Giao dịch gần đây",
        "no_transactions" to "Chưa có giao dịch nào được ghi chép.",
        "quick_actions" to "Phím tắt nhanh",
        "scan_receipt" to "Quét AI",
        "add_expense" to "Thêm chi",
        "add_income" to "Thêm thu",

        "all" to "Tất cả",
        "waiting_sync" to "Chờ đồng bộ",
        "sync_now" to "Đồng bộ ngay",
        "sync_status" to "Đồng bộ",
        "synced" to "Đã đồng bộ",
        "pending" to "Chưa đồng bộ",
        "transaction_detail" to "Chi tiết giao dịch",
        "delete_confirm" to "Bạn có chắc chắn muốn xóa giao dịch này?",
        "delete" to "Xóa",
        "edit" to "Sửa",

        "amount" to "Số tiền",
        "title" to "Sản phẩm",
        "category" to "Danh mục",
        "account" to "Tài khoản",
        "date" to "Ngày giao dịch",
        "note" to "Ghi chú (Tùy chọn)",
        "save" to "Lưu",
        "fill_all_fields" to "Vui lòng nhập đầy đủ các trường thông tin.",
        "input_title_error" to "Vui lòng nhập tên khoản chi.",
        "input_title_income_error" to "Vui lòng nhập tên khoản thu.",

        "income_expense_chart" to "Biểu đồ Thu/Chi",
        "advanced_sync_options" to "[+] Tùy chọn nâng cao (Đồng bộ PC)",
        "hide_advanced_sync" to "[-] Ẩn tùy chọn nâng cao (Đồng bộ PC)",

        "Ăn uống" to "Ăn uống",
        "Di chuyển" to "Di chuyển",
        "Mua sắm" to "Mua sắm",
        "Giải trí" to "Giải trí",
        "Nhà ở" to "Nhà ở",
        "Y tế" to "Y tế",
        "Khác" to "Khác",
        "Lương" to "Lương",
        "Thưởng" to "Thưởng",
        "Đầu tư" to "Đầu tư",
        "Quà tặng" to "Quà tặng",

        "Tiền mặt" to "Tiền mặt",
        "Tài khoản ngân hàng" to "Tài khoản ngân hàng",
        "Ví MoMo" to "Ví MoMo",

        "report_dashboard" to "Bảng phân tích tài chính",
        "time_filter" to "Chọn thời gian",
        "today" to "Hôm nay",
        "this_week" to "Tuần này",
        "this_month" to "Tháng này",
        "this_year" to "Năm nay",
        "custom" to "Tùy chọn",
        "remaining" to "Còn lại",
        "category_stats" to "Phân tích theo hạng mục",

        "account_title" to "Quản lý Tài khoản",
        "add_account" to "Thêm tài khoản mới",
        "edit_account" to "Sửa tài khoản",
        "account_name" to "Tên tài khoản (Ví dụ: Tiền mặt)",
        "initial_balance" to "Số dư ban đầu",
        "default_currency" to "Đồng tiền mặc định",
        "edit_category" to "Sửa danh mục",
        "save_changes" to "Lưu thay đổi",
        "delete_account_confirm" to "Bạn có chắc chắn muốn xóa tài khoản này? Tất cả các khoản chi tiêu dưới tài khoản này vẫn sẽ giữ nguyên nhưng tên liên kết có thể mất.",
        "delete_category_confirm" to "Bạn có chắc chắn muốn xóa danh mục này?",

        "budget_title" to "Quản lý Ngân sách và Hạn mức",
        "add_budget" to "Thêm hạn mức chi",
        "budget_name" to "Tên ngân sách",
        "budget_amount" to "Hạn mức tối đa",
        "budget_period" to "Chu kỳ ngân sách",
        "weekly" to "Hàng tuần",
        "monthly" to "Hàng tháng",
        "start_date" to "Ngày bắt đầu",
        "end_date" to "Ngày kết thúc",

        "category_title" to "Quản lý Danh mục",
        "add_category" to "Thêm danh mục mới",
        "expense_categories" to "Danh mục Chi",
        "income_categories" to "Danh mục Thu",

        "recurring_title" to "Giao dịch Định kỳ tự động",
        "add_recurring" to "Thêm chu kỳ giao dịch",
        "recurring_name" to "Tên giao dịch định kỳ",
        "cycle_type" to "Tần suất lặp",
        "daily" to "Hàng ngày",
        "monthly_cycle" to "Hàng tháng",
        "yearly" to "Hàng năm",

        "split_bill_title" to "Chia tiền nhóm & Bạn bè",
        "add_split" to "Tạo bill chia sẻ",
        "participants" to "Danh sách người tham gia (cách nhau bằng dấu phẩy)",
        "payer" to "Người chi trả thực tế",
        "total_amount" to "Tổng tiền hóa đơn",
        "share_per_person" to "Phần chia mỗi người",
        "settlements" to "Gợi ý phương án thanh toán",
        "owes" to "nợ",
        "to" to "cho",

        // Backup
        "backup_title" to "Sao lưu và khôi phục",
        "backup_section" to "Google Drive",
        "backup_now" to "Sao lưu ngay",
        "restore_now" to "Khôi phục từ Drive",
        "auto_backup" to "Tự động sao lưu lúc 8:00 tối",
        "last_backup" to "Sao lưu gần nhất",
        "no_backup_yet" to "Chưa có bản sao lưu",
        "backup_success" to "Sao lưu thành công",
        "backup_failed" to "Sao lưu thất bại",
        "backup_running" to "Đang sao lưu...",
        "restore_confirm_title" to "Xác nhận khôi phục",
        "restore_confirm_body" to "Dữ liệu hiện tại sẽ bị ghi đè bởi bản sao lưu. Bạn có chắc chắn?",
        "sign_in_required" to "Đăng nhập Google để sao lưu",
        "google_signed_in" to "Đã đăng nhập",
        "google_sign_in_btn" to "Đăng nhập với Google",
        "google_sign_out" to "Đăng xuất Google",

        "auth_title" to "Tài khoản Thần Tài",
        "user_profile" to "Hồ sơ người dùng",
        "name" to "Họ tên người dùng",
        "email" to "Địa chỉ Email",
        "google_login" to "Liên kết Google Account",
        "login" to "Đăng nhập",
        "register" to "Đăng ký thành viên",
        "logout" to "Đăng xuất",
        "server_url" to "Địa chỉ máy chủ Backend PC",
        "not_logged_in" to "Chưa đăng nhập",
        "logged_in_as" to "Tài khoản:",

        "language" to "Ngôn ngữ / Language",
        "change_lang_confirm" to "Xác nhận chuyển đổi ngôn ngữ",
        "change_lang_body" to "Bạn có chắc chắn muốn chuyển ngôn ngữ sang Tiếng Việt?",
        "confirm" to "Xác nhận",
        "cancel" to "Hủy bỏ",

        "ocr_running" to "AI đang đọc hóa đơn...",
        "ocr_desc" to "Trình xử lý AI thông minh sẽ trích xuất tên sản phẩm và số tiền chi tiêu từ ảnh hóa đơn.",
        "ocr_draft_label" to "Duyệt thông tin quét hóa đơn (Bản nháp)",
        "take_photo" to "Chụp ảnh hóa đơn",
        "mock_select_receipt_label" to "Chọn hóa đơn mẫu để thử quét AI:",
        "pick_from_gallery" to "Chọn từ thư viện",

        "choose_language" to "Chọn ngôn ngữ",
        "choose_language_subtitle" to "Chọn ngôn ngữ bạn muốn sử dụng",
        "continue_btn" to "Tiếp tục"
    )

    private val en = mapOf(
        "app_name" to "Lucky Wallet",
        "home" to "Home",
        "history" to "History",
        "reports" to "Reports",
        "tools" to "Tools",
        "settings" to "Settings",

        "current_balance" to "Total Available Balance",
        "income" to "Income",
        "expense" to "Expense",
        "recent_transactions" to "Recent Transactions",
        "no_transactions" to "No transactions recorded yet.",
        "quick_actions" to "Quick Actions",
        "scan_receipt" to "Scan AI",
        "add_expense" to "Add Expense",
        "add_income" to "Add Income",

        "all" to "All",
        "waiting_sync" to "Pending Sync",
        "sync_now" to "Sync Now",
        "sync_status" to "Sync Status",
        "synced" to "Synced",
        "pending" to "Pending",
        "transaction_detail" to "Transaction Detail",
        "delete_confirm" to "Are you sure you want to delete this transaction?",
        "delete" to "Delete",
        "edit" to "Edit",

        "amount" to "Amount",
        "title" to "Title/Item details",
        "category" to "Category",
        "account" to "Account",
        "date" to "Date",
        "note" to "Note (Optional)",
        "save" to "Save",
        "fill_all_fields" to "Please fill in all details.",
        "input_title_error" to "Please enter transaction title.",
        "input_title_income_error" to "Please enter income title.",

        "income_expense_chart" to "Income/Expense Chart",
        "advanced_sync_options" to "[+] Advanced Options (PC Sync)",
        "hide_advanced_sync" to "[-] Hide advanced options",

        "Ăn uống" to "Food & Drink",
        "Di chuyển" to "Transport",
        "Mua sắm" to "Shopping",
        "Giải trí" to "Entertainment",
        "Nhà ở" to "Housing",
        "Y tế" to "Healthcare",
        "Khác" to "Others",
        "Lương" to "Salary",
        "Thưởng" to "Bonus",
        "Đầu tư" to "Investment",
        "Quà tặng" to "Gift",

        "Tiền mặt" to "Cash",
        "Tài khoản ngân hàng" to "Bank Account",
        "Ví MoMo" to "MoMo Wallet",

        "report_dashboard" to "Financial Analytics Dashboard",
        "time_filter" to "Select Period",
        "today" to "Today",
        "this_week" to "This Week",
        "this_month" to "This Month",
        "this_year" to "This Year",
        "custom" to "Custom",
        "remaining" to "Remaining",
        "category_stats" to "Breakdown by Category",

        "account_title" to "Manage Accounts",
        "add_account" to "Add New Account",
        "edit_account" to "Edit Account",
        "account_name" to "Account Name (e.g., Cash)",
        "initial_balance" to "Initial Balance",
        "default_currency" to "Default Currency",
        "edit_category" to "Edit Category",
        "save_changes" to "Save Changes",
        "delete_account_confirm" to "Are you sure you want to delete this account? Existing transactions will remain as history.",
        "delete_category_confirm" to "Are you sure you want to delete this category?",

        "budget_title" to "Budgets & Limits",
        "add_budget" to "Add Budget Limit",
        "budget_name" to "Budget Name",
        "budget_amount" to "Budget Threshold",
        "budget_period" to "Budget Cycle",
        "weekly" to "Weekly",
        "monthly" to "Monthly",
        "start_date" to "Start Date",
        "end_date" to "End Date",

        "category_title" to "Categories Management",
        "add_category" to "Add New Category",
        "expense_categories" to "Expense Categories",
        "income_categories" to "Income Categories",

        "recurring_title" to "Automated Recurring Transactions",
        "add_recurring" to "Add Recurring Rule",
        "recurring_name" to "Schedule Name",
        "cycle_type" to "Interval Frequency",
        "daily" to "Daily",
        "monthly_cycle" to "Monthly",
        "yearly" to "Yearly",

        "split_bill_title" to "Split Bills with Friends",
        "add_split" to "Create Split Bill",
        "participants" to "Participants list (separated by commas)",
        "payer" to "Payer",
        "total_amount" to "Total Amount",
        "share_per_person" to "Share Per Person",
        "settlements" to "Suggested Debt Settlements",
        "owes" to "owes",
        "to" to "to",

        // Backup
        "backup_title" to "Backup & Restore",
        "backup_section" to "Google Drive",
        "backup_now" to "Backup Now",
        "restore_now" to "Restore from Drive",
        "auto_backup" to "Auto backup at 8:00 PM daily",
        "last_backup" to "Last backup",
        "no_backup_yet" to "No backup yet",
        "backup_success" to "Backup successful",
        "backup_failed" to "Backup failed",
        "backup_running" to "Backing up...",
        "restore_confirm_title" to "Confirm Restore",
        "restore_confirm_body" to "Current data will be overwritten by the backup. Are you sure?",
        "sign_in_required" to "Sign in with Google to backup",
        "google_signed_in" to "Signed in",
        "google_sign_in_btn" to "Sign in with Google",
        "google_sign_out" to "Sign out",

        "auth_title" to "Lucky Account",
        "user_profile" to "User Profile",
        "name" to "Full Name",
        "email" to "Email Address",
        "google_login" to "Link with Google Account",
        "login" to "Login",
        "register" to "Register Account",
        "logout" to "Logout",
        "server_url" to "Backend Host URL",
        "not_logged_in" to "Not Logged In",
        "logged_in_as" to "Logged in:",

        "language" to "Ngôn ngữ / Language",
        "change_lang_confirm" to "Change Language",
        "change_lang_body" to "Are you sure you want to change the language to English?",
        "confirm" to "Confirm",
        "cancel" to "Cancel",

        "ocr_running" to "AI is analyzing receipt...",
        "ocr_desc" to "Smart AI scanner will automatically extract amounts and item titles safely.",
        "ocr_draft_label" to "Review Scanned Draft",
        "take_photo" to "Take Photo",
        "mock_select_receipt_label" to "Select sample receipt to test AI parsing:",
        "pick_from_gallery" to "Pick from Gallery",

        "choose_language" to "Choose Language",
        "choose_language_subtitle" to "Select your preferred language",
        "continue_btn" to "Continue"
    )

    private val de = mapOf(
        "app_name" to "Lucky Wallet",
        "home" to "Startseite",
        "history" to "Verlauf",
        "reports" to "Berichte",
        "tools" to "Werkzeuge",
        "settings" to "Einstellungen",

        "current_balance" to "Verfügbares Guthaben",
        "income" to "Einnahmen",
        "expense" to "Ausgaben",
        "recent_transactions" to "Letzte Transaktionen",
        "no_transactions" to "Noch keine Transaktionen erfasst.",
        "quick_actions" to "Schnellaktionen",
        "scan_receipt" to "KI-Scan",
        "add_expense" to "Ausgabe",
        "add_income" to "Einnahme",

        "all" to "Alle",
        "waiting_sync" to "Warten auf Sync",
        "sync_now" to "Jetzt synchronisieren",
        "sync_status" to "Sync-Status",
        "synced" to "Synchronisiert",
        "pending" to "Ausstehend",
        "transaction_detail" to "Transaktionsdetails",
        "delete_confirm" to "Möchten Sie diese Transaktion wirklich löschen?",
        "delete" to "Löschen",
        "edit" to "Bearbeiten",

        "amount" to "Betrag",
        "title" to "Titel/Artikel",
        "category" to "Kategorie",
        "account" to "Konto",
        "date" to "Datum",
        "note" to "Notiz (Optional)",
        "save" to "Speichern",
        "fill_all_fields" to "Bitte füllen Sie alle Felder aus.",
        "input_title_error" to "Bitte geben Sie einen Titel ein.",
        "input_title_income_error" to "Bitte geben Sie einen Einnahmetitel ein.",

        "income_expense_chart" to "Einnahmen/Ausgaben-Diagramm",
        "advanced_sync_options" to "[+] Erweiterte Optionen (PC-Sync)",
        "hide_advanced_sync" to "[-] Erweiterte Optionen ausblenden",

        "Ăn uống" to "Essen & Trinken",
        "Di chuyển" to "Transport",
        "Mua sắm" to "Einkaufen",
        "Giải trí" to "Unterhaltung",
        "Nhà ở" to "Wohnen",
        "Y tế" to "Gesundheit",
        "Khác" to "Sonstiges",
        "Lương" to "Gehalt",
        "Thưởng" to "Bonus",
        "Đầu tư" to "Investition",
        "Quà tặng" to "Geschenk",

        "Tiền mặt" to "Bargeld",
        "Tài khoản ngân hàng" to "Bankkonto",
        "Ví MoMo" to "MoMo-Wallet",

        "report_dashboard" to "Finanzanalyse-Dashboard",
        "time_filter" to "Zeitraum wählen",
        "today" to "Heute",
        "this_week" to "Diese Woche",
        "this_month" to "Dieser Monat",
        "this_year" to "Dieses Jahr",
        "custom" to "Benutzerdefiniert",
        "remaining" to "Verbleibend",
        "category_stats" to "Aufschlüsselung nach Kategorie",

        "account_title" to "Konten verwalten",
        "add_account" to "Neues Konto hinzufügen",
        "edit_account" to "Konto bearbeiten",
        "account_name" to "Kontoname (z.B. Bargeld)",
        "initial_balance" to "Anfangssaldo",
        "default_currency" to "Standardwährung",
        "edit_category" to "Kategorie bearbeiten",
        "save_changes" to "Änderungen speichern",
        "delete_account_confirm" to "Möchten Sie dieses Konto wirklich löschen? Vorhandene Transaktionen bleiben als Verlauf erhalten.",
        "delete_category_confirm" to "Möchten Sie diese Kategorie wirklich löschen?",

        "budget_title" to "Budgets & Limits",
        "add_budget" to "Budgetlimit hinzufügen",
        "budget_name" to "Budgetname",
        "budget_amount" to "Budgetgrenze",
        "budget_period" to "Budgetzyklus",
        "weekly" to "Wöchentlich",
        "monthly" to "Monatlich",
        "start_date" to "Startdatum",
        "end_date" to "Enddatum",

        "category_title" to "Kategorien verwalten",
        "add_category" to "Neue Kategorie hinzufügen",
        "expense_categories" to "Ausgabenkategorien",
        "income_categories" to "Einnahmenkategorien",

        "recurring_title" to "Automatische wiederkehrende Transaktionen",
        "add_recurring" to "Wiederkehrende Regel hinzufügen",
        "recurring_name" to "Zeitplanname",
        "cycle_type" to "Intervallhäufigkeit",
        "daily" to "Täglich",
        "monthly_cycle" to "Monatlich",
        "yearly" to "Jährlich",

        "split_bill_title" to "Rechnungen mit Freunden teilen",
        "add_split" to "Geteilte Rechnung erstellen",
        "participants" to "Teilnehmerliste (durch Kommas getrennt)",
        "payer" to "Zahler",
        "total_amount" to "Gesamtbetrag",
        "share_per_person" to "Anteil pro Person",
        "settlements" to "Vorgeschlagene Schuldenbegleichung",
        "owes" to "schuldet",
        "to" to "an",

        "backup_title" to "Sichern & Wiederherstellen",
        "backup_section" to "Google Drive",
        "backup_now" to "Jetzt sichern",
        "restore_now" to "Von Drive wiederherstellen",
        "auto_backup" to "Automatische Sicherung täglich um 20:00 Uhr",
        "last_backup" to "Letzte Sicherung",
        "no_backup_yet" to "Noch keine Sicherung",
        "backup_success" to "Sicherung erfolgreich",
        "backup_failed" to "Sicherung fehlgeschlagen",
        "backup_running" to "Sichern...",
        "restore_confirm_title" to "Wiederherstellung bestätigen",
        "restore_confirm_body" to "Aktuelle Daten werden durch die Sicherung überschrieben. Sind Sie sicher?",
        "sign_in_required" to "Zum Sichern mit Google anmelden",
        "google_signed_in" to "Angemeldet",
        "google_sign_in_btn" to "Mit Google anmelden",
        "google_sign_out" to "Abmelden",

        "auth_title" to "Lucky-Konto",
        "user_profile" to "Benutzerprofil",
        "name" to "Vollständiger Name",
        "email" to "E-Mail-Adresse",
        "google_login" to "Mit Google-Konto verknüpfen",
        "login" to "Anmelden",
        "register" to "Konto registrieren",
        "logout" to "Abmelden",
        "server_url" to "Backend-Host-URL",
        "not_logged_in" to "Nicht angemeldet",
        "logged_in_as" to "Angemeldet:",

        "language" to "Sprache / Language",
        "change_lang_confirm" to "Sprache ändern",
        "change_lang_body" to "Möchten Sie die Sprache wirklich auf Deutsch ändern?",
        "confirm" to "Bestätigen",
        "cancel" to "Abbrechen",

        "ocr_running" to "KI analysiert Beleg...",
        "ocr_desc" to "Der intelligente KI-Scanner extrahiert automatisch Beträge und Artikelnamen.",
        "ocr_draft_label" to "Gescannten Entwurf prüfen",
        "take_photo" to "Foto aufnehmen",
        "mock_select_receipt_label" to "Beispielbeleg zum Testen des KI-Scans auswählen:",
        "pick_from_gallery" to "Aus Galerie wählen",

        "choose_language" to "Sprache wählen",
        "choose_language_subtitle" to "Wählen Sie Ihre bevorzugte Sprache",
        "continue_btn" to "Weiter"
    )

    private val hi = mapOf(
        "app_name" to "Lucky Wallet",
        "home" to "होम",
        "history" to "इतिहास",
        "reports" to "रिपोर्ट",
        "tools" to "उपकरण",
        "settings" to "सेटिंग्स",

        "current_balance" to "उपलब्ध कुल शेष",
        "income" to "आय",
        "expense" to "व्यय",
        "recent_transactions" to "हाल के लेनदेन",
        "no_transactions" to "अभी तक कोई लेनदेन दर्ज नहीं किया गया।",
        "quick_actions" to "त्वरित क्रियाएँ",
        "scan_receipt" to "एआई स्कैन",
        "add_expense" to "व्यय जोड़ें",
        "add_income" to "आय जोड़ें",

        "all" to "सभी",
        "waiting_sync" to "सिंक लंबित",
        "sync_now" to "अभी सिंक करें",
        "sync_status" to "सिंक स्थिति",
        "synced" to "सिंक किया गया",
        "pending" to "लंबित",
        "transaction_detail" to "लेनदेन विवरण",
        "delete_confirm" to "क्या आप वाकई इस लेनदेन को हटाना चाहते हैं?",
        "delete" to "हटाएं",
        "edit" to "संपादित करें",

        "amount" to "राशि",
        "title" to "शीर्षक/वस्तु",
        "category" to "श्रेणी",
        "account" to "खाता",
        "date" to "तारीख",
        "note" to "टिप्पणी (वैकल्पिक)",
        "save" to "सहेजें",
        "fill_all_fields" to "कृपया सभी विवरण भरें।",
        "input_title_error" to "कृपया लेनदेन शीर्षक दर्ज करें।",
        "input_title_income_error" to "कृपया आय शीर्षक दर्ज करें।",

        "income_expense_chart" to "आय/व्यय चार्ट",
        "advanced_sync_options" to "[+] उन्नत विकल्प (पीसी सिंक)",
        "hide_advanced_sync" to "[-] उन्नत विकल्प छिपाएं",

        "Ăn uống" to "खाना और पेय",
        "Di chuyển" to "परिवहन",
        "Mua sắm" to "खरीदारी",
        "Giải trí" to "मनोरंजन",
        "Nhà ở" to "आवास",
        "Y tế" to "स्वास्थ्य",
        "Khác" to "अन्य",
        "Lương" to "वेतन",
        "Thưởng" to "बोनस",
        "Đầu tư" to "निवेश",
        "Quà tặng" to "उपहार",

        "Tiền mặt" to "नकद",
        "Tài khoản ngân hàng" to "बैंक खाता",
        "Ví MoMo" to "MoMo वॉलेट",

        "report_dashboard" to "वित्तीय विश्लेषण डैशबोर्ड",
        "time_filter" to "अवधि चुनें",
        "today" to "आज",
        "this_week" to "इस सप्ताह",
        "this_month" to "इस महीने",
        "this_year" to "इस वर्ष",
        "custom" to "कस्टम",
        "remaining" to "शेष",
        "category_stats" to "श्रेणी के अनुसार विवरण",

        "account_title" to "खाते प्रबंधित करें",
        "add_account" to "नया खाता जोड़ें",
        "edit_account" to "खाता संपादित करें",
        "account_name" to "खाता नाम (जैसे नकद)",
        "initial_balance" to "प्रारंभिक शेष",
        "default_currency" to "डिफ़ॉल्ट मुद्रा",
        "edit_category" to "श्रेणी संपादित करें",
        "save_changes" to "परिवर्तन सहेजें",
        "delete_account_confirm" to "क्या आप वाकई इस खाते को हटाना चाहते हैं? मौजूदा लेनदेन इतिहास के रूप में बने रहेंगे।",
        "delete_category_confirm" to "क्या आप वाकई इस श्रेणी को हटाना चाहते हैं?",

        "budget_title" to "बजट और सीमाएं",
        "add_budget" to "बजट सीमा जोड़ें",
        "budget_name" to "बजट नाम",
        "budget_amount" to "बजट सीमा",
        "budget_period" to "बजट चक्र",
        "weekly" to "साप्ताहिक",
        "monthly" to "मासिक",
        "start_date" to "प्रारंभ तिथि",
        "end_date" to "समाप्ति तिथि",

        "category_title" to "श्रेणियां प्रबंधित करें",
        "add_category" to "नई श्रेणी जोड़ें",
        "expense_categories" to "व्यय श्रेणियां",
        "income_categories" to "आय श्रेणियां",

        "recurring_title" to "स्वचालित आवर्ती लेनदेन",
        "add_recurring" to "आवर्ती नियम जोड़ें",
        "recurring_name" to "अनुसूची नाम",
        "cycle_type" to "अंतराल आवृत्ति",
        "daily" to "दैनिक",
        "monthly_cycle" to "मासिक",
        "yearly" to "वार्षिक",

        "split_bill_title" to "दोस्तों के साथ बिल बांटें",
        "add_split" to "विभाजित बिल बनाएं",
        "participants" to "प्रतिभागी सूची (अल्पविराम से अलग)",
        "payer" to "भुगतानकर्ता",
        "total_amount" to "कुल राशि",
        "share_per_person" to "प्रति व्यक्ति हिस्सा",
        "settlements" to "सुझाए गए ऋण निपटान",
        "owes" to "देना है",
        "to" to "को",

        "backup_title" to "बैकअप और पुनर्स्थापना",
        "backup_section" to "Google Drive",
        "backup_now" to "अभी बैकअप लें",
        "restore_now" to "Drive से पुनर्स्थापित करें",
        "auto_backup" to "प्रतिदिन रात 8:00 बजे स्वतः बैकअप",
        "last_backup" to "अंतिम बैकअप",
        "no_backup_yet" to "अभी तक कोई बैकअप नहीं",
        "backup_success" to "बैकअप सफल",
        "backup_failed" to "बैकअप विफल",
        "backup_running" to "बैकअप हो रहा है...",
        "restore_confirm_title" to "पुनर्स्थापना की पुष्टि करें",
        "restore_confirm_body" to "वर्तमान डेटा बैकअप द्वारा अधिलेखित हो जाएगा। क्या आप निश्चित हैं?",
        "sign_in_required" to "बैकअप के लिए Google से साइन इन करें",
        "google_signed_in" to "साइन इन किया गया",
        "google_sign_in_btn" to "Google से साइन इन करें",
        "google_sign_out" to "साइन आउट",

        "auth_title" to "Lucky खाता",
        "user_profile" to "उपयोगकर्ता प्रोफ़ाइल",
        "name" to "पूरा नाम",
        "email" to "ईमेल पता",
        "google_login" to "Google खाते से लिंक करें",
        "login" to "लॉग इन",
        "register" to "खाता पंजीकृत करें",
        "logout" to "लॉग आउट",
        "server_url" to "बैकएंड होस्ट URL",
        "not_logged_in" to "लॉग इन नहीं है",
        "logged_in_as" to "लॉग इन:",

        "language" to "भाषा / Language",
        "change_lang_confirm" to "भाषा बदलें",
        "change_lang_body" to "क्या आप वाकई भाषा को हिंदी में बदलना चाहते हैं?",
        "confirm" to "पुष्टि करें",
        "cancel" to "रद्द करें",

        "ocr_running" to "एआई रसीद का विश्लेषण कर रहा है...",
        "ocr_desc" to "स्मार्ट एआई स्कैनर स्वचालित रूप से राशि और वस्तु के नाम निकालेगा।",
        "ocr_draft_label" to "स्कैन किए गए मसौदे की समीक्षा करें",
        "take_photo" to "फोटो लें",
        "mock_select_receipt_label" to "एआई स्कैन परीक्षण के लिए नमूना रसीद चुनें:",
        "pick_from_gallery" to "गैलरी से चुनें",

        "choose_language" to "भाषा चुनें",
        "choose_language_subtitle" to "अपनी पसंदीदा भाषा चुनें",
        "continue_btn" to "जारी रखें"
    )

    fun getString(key: String, lang: AppLanguage): String {
        val table = when (lang) {
            AppLanguage.VIETNAMESE -> vi
            AppLanguage.ENGLISH -> en
            AppLanguage.GERMAN -> de
            AppLanguage.HINDI -> hi
        }
        // Fallback: bảng ngôn ngữ hiện tại → tiếng Anh → tiếng Việt → chính key
        return table[key] ?: en[key] ?: vi[key] ?: key
    }
}

val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.VIETNAMESE }

@Composable
fun LocalizedText(key: String, language: AppLanguage) {
    androidx.compose.material3.Text(
        text = Localization.getString(key, language)
    )
}
